scan_filter_chain:
- name: box_filter1
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: world
    max_x: -1
    max_y: 3.5
    max_z: 5
    min_x: -2.2
    min_y: 2
    min_z: -5
    invert: false
- name: box_filter2
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: world
    max_x: 2.2
    max_y: 3.5
    max_z: 5
    min_x: 1
    min_y: 2
    min_z: -5
    invert: false

